version: "3.7"
services:
  crm-db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=mildang-crm
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=mildang
      - MYSQL_PASSWORD=mildang
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql